name: Daily Streak

on:
  schedule:
    - cron: "0 12 * * *"  # todo dia ao meio-dia UTC
  workflow_dispatch:      # permite rodar manualmente

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # necessário pra push

    steps:
      # 1️⃣ Pega o código do repo
      - uses: actions/checkout@v4

      # 2️⃣ Configura o Git com seu usuário
      - name: Configure Git
        run: |
          git config user.name "amara-mayers"
          git config user.email "rewardsnum@gmail.com"

      # 3️⃣ Commit automático diário (mesmo sem mudanças)
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Streak diário - $(date +'%Y-%m-%d')"
          skip_dirty_check: true
          commit_options: '--allow-empty'
