import os
from datetime import datetime

# Caminho do seu repositório local (onde você quer os commits)
repo_path = r"C:\caminho\do\seu\repositorio"

# Mensagem do commit com a data
commit_message = f"Commit automático streak - {datetime.now().strftime('%Y-%m-%d')}"

# Muda para a pasta do repo
os.chdir(repo_path)

# Adiciona todas as mudanças (se não houver mudanças, ainda assim cria um commit vazio)
os.system("git add .")

# Commit
os.system(f'git commit -m "{commit_message}" --allow-empty')  # <-- commit vazio permite criar streak sem mudar arquivos

# Push pro GitHub
os.system("git push")
