name: Streak diário

on:
  schedule:
    - cron: "0 12 * * *"  # todo dia ao meio-dia (UTC)
  workflow_dispatch:       # permite rodar manualmente também

jobs:
  commit-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "SeuNome"
          git config user.email "seuemail@example.com"

      - name: Criar commit vazio
        run: |
          git commit --allow-empty -m "Commit automático streak - $(date +'%Y-%m-%d')" || echo "Nada para commitar"
      
      - name: Push pro GitHub
        run: git push
